# CMake generated Testfile for 
# Source directory: /app/tests
# Build directory: /app/build_quality/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_core "/app/build_quality/tests/test_core")
set_tests_properties(test_core PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;12;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_10 "/app/build_quality/tests/test_service_10")
set_tests_properties(test_service_10 PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;13;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_22 "/app/build_quality/tests/test_service_22")
set_tests_properties(test_service_22 PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;14;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_27 "/app/build_quality/tests/test_service_27")
set_tests_properties(test_service_27 PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;15;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_3E "/app/build_quality/tests/test_service_3E")
set_tests_properties(test_service_3E PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;16;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_11 "/app/build_quality/tests/test_service_11")
set_tests_properties(test_service_11 PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;17;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_28 "/app/build_quality/tests/test_service_28")
set_tests_properties(test_service_28 PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;18;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_did "/app/build_quality/tests/test_service_did")
set_tests_properties(test_service_did PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;19;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_timing "/app/build_quality/tests/test_timing")
set_tests_properties(test_timing PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;20;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_29 "/app/build_quality/tests/test_service_29")
set_tests_properties(test_service_29 PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;21;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_dtc "/app/build_quality/tests/test_service_dtc")
set_tests_properties(test_service_dtc PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;22;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_flash "/app/build_quality/tests/test_service_flash")
set_tests_properties(test_service_flash PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;23;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_mem "/app/build_quality/tests/test_service_mem")
set_tests_properties(test_service_mem PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;24;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_osal "/app/build_quality/tests/test_osal")
set_tests_properties(test_osal PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;25;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_endian "/app/build_quality/tests/test_endian")
set_tests_properties(test_endian PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;26;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_fuzz_core "/app/build_quality/tests/test_fuzz_core")
set_tests_properties(test_fuzz_core PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;27;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_transport "/app/build_quality/tests/test_transport")
set_tests_properties(test_transport PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;28;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_negative "/app/build_quality/tests/test_service_negative")
set_tests_properties(test_service_negative PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;30;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_service_2E "/app/build_quality/tests/test_service_2E")
set_tests_properties(test_service_2E PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;31;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_safety_gate "/app/build_quality/tests/test_safety_gate")
set_tests_properties(test_safety_gate PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;32;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_async "/app/build_quality/tests/test_async")
set_tests_properties(test_async PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;33;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_nvm_persistence "/app/build_quality/tests/test_nvm_persistence")
set_tests_properties(test_nvm_persistence PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;34;add_uds_test;/app/tests/CMakeLists.txt;0;")
add_test(test_integration "/app/build_quality/tests/test_integration")
set_tests_properties(test_integration PROPERTIES  _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;9;add_test;/app/tests/CMakeLists.txt;35;add_uds_test;/app/tests/CMakeLists.txt;0;")
