#!/usr/bin/env python3
# Copyright (c) 2026 Andrii Shylenko
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

"""
UDS Test Generator

Generates Python integration test scaffolding from service specifications.

Usage:
    python generate_tests.py --service 0x22 --output tests/integration/
"""

import argparse
import sys
from pathlib import Path

# Test template - use double {{ }} to escape braces in f-strings
TEST_TEMPLATE = '''#!/usr/bin/env python3
"""
Auto-generated integration test for UDS Service {service_hex}
{service_name}

Generated by generate_tests.py
DO NOT EDIT MANUALLY - Regenerate from spec
"""

import pytest
from uds_test_client import UDSClient

@pytest.fixture
def uds():
    """Create UDS client connection"""
    client = UDSClient(interface='socketcan', channel='vcan0', address=0x7DF)
    yield client
    client.close()


def test_{test_name}_positive(uds):
    """Test {service_name} - Positive Response"""
    request = bytes([{request_bytes}])
    response = uds.send(request, timeout=1.0)
    
    assert response is not None, "No response received"
    assert response[0] == {positive_response_sid}, "Expected positive response"
    # TODO: Add specific assertions for response data


def test_{test_name}_negative_incorrect_length(uds):
    """Test {service_name} - Negative Response (Incorrect Length)"""
    request = bytes([{service_hex}])  # Too short
    response = uds.send(request, timeout=1.0)
    
    assert response is not None
    assert response[0] == 0x7F, "Expected negative response"
    assert response[1] == {service_hex}, "NRC should reference original SID"
    assert response[2] == 0x13, "Expected NRC 0x13 (Incorrect Message Length)"


def test_{test_name}_negative_service_not_supported_in_session(uds):
    """Test {service_name} - Wrong Session"""
    # TODO: Implement session-specific testing
    pass
'''


SERVICE_SPECS = {
    0x10: {
        'name': 'Diagnostic Session Control',
        'test_name': 'session_control',
        'min_length': 2,
        'request_example': [0x10, 0x03],  # Extended session
        'positive_sid': 0x50,
    },
    0x22: {
        'name': 'Read Data By Identifier',
        'test_name': 'read_data_by_id',
        'min_length': 3,
        'request_example': [0x22, 0xF1, 0x90],  # Read VIN
        'positive_sid': 0x62,
    },
    0x27: {
        'name': 'Security Access',
        'test_name': 'security_access',
        'min_length': 2,
        'request_example': [0x27, 0x01],  # Request Seed
        'positive_sid': 0x67,
    },
    0x2E: {
        'name': 'Write Data By Identifier',
        'test_name': 'write_data_by_id',
        'min_length': 3,
        'request_example': [0x2E, 0xF1, 0x00, 0xAA],
        'positive_sid': 0x6E,
    },
    0x3E: {
        'name': 'Tester Present',
        'test_name': 'tester_present',
        'min_length': 2,
        'request_example': [0x3E, 0x00],
        'positive_sid': 0x7E,
    },
    0x31: {
        'name': 'Routine Control',
        'test_name': 'routine_control',
        'min_length': 4,
        'request_example': [0x31, 0x01, 0xFF, 0x00],  # Start Routine
        'positive_sid': 0x71,
    },
}


def generate_test(service_id: int, output_dir: Path):
    """Generate test file for a specific service"""
    
    if service_id not in SERVICE_SPECS:
        print(f"Warning: Service {service_id:#x} not in spec database", file=sys.stderr)
        print("Generating generic template...")
        spec = {
            'name': f'Service {service_id:#x}',
            'test_name': f'service_{service_id:02x}',
            'min_length': 1,
            'request_example': [service_id],
            'positive_sid': service_id + 0x40,
        }
    else:
        spec = SERVICE_SPECS[service_id]
    
    # Format request bytes as hex strings
    request_bytes = ', '.join(f'0x{b:02x}' for b in spec['request_example'])
    
    test_code = TEST_TEMPLATE.format(
        service_hex=f'0x{service_id:02x}',
        service_name=spec['name'],
        test_name=spec['test_name'],
        request_bytes=request_bytes,
        positive_response_sid=f"0x{spec['positive_sid']:02x}",
    )
    
    output_file = output_dir / f"test_{spec['test_name']}.py"
    output_file.write_text(test_code)
    
    print(f"✅ Generated: {output_file}")


def generate_all_tests(output_dir: Path):
    """Generate tests for all known services"""
    for service_id in SERVICE_SPECS:
        generate_test(service_id, output_dir)


def main():
    parser = argparse.ArgumentParser(description='Generate UDS integration tests')
    parser.add_argument('--service', type=lambda x: int(x, 0), help='Service ID (e.g., 0x22)')
    parser.add_argument('--all', action='store_true', help='Generate tests for all services')
    parser.add_argument('--output', type=Path, default=Path('tests/integration'), help='Output directory')
    
    args = parser.parse_args()
    
    if not args.service and not args.all:
        parser.error("Specify --service or --all")
    
    args.output.mkdir(parents=True, exist_ok=True)
    
    if args.all:
        print(f"Generating tests for {len(SERVICE_SPECS)} services...")
        generate_all_tests(args.output)
    else:
        generate_test(args.service, args.output)
    
    print(f"\n📝 To run tests:")
    print(f"   cd {args.output}")
    print(f"   pytest -v")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
