#!/usr/bin/env python3
# Copyright (c) 2026 Andrii Shylenko
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

"""
Auto-generated integration test for UDS Service 0x2e
Write Data By Identifier

Generated by generate_tests.py
DO NOT EDIT MANUALLY - Regenerate from spec
"""

import pytest
from uds_test_client import UDSClient

@pytest.fixture
def uds():
    """Create UDS client connection"""
    client = UDSClient(interface='socketcan', channel='vcan0', address=0x7DF)
    yield client
    client.close()


def test_write_data_by_id_positive(uds):
    """Test Write Data By Identifier - Positive Response"""
    request = bytes([0x2e, 0xf1, 0x00, 0xaa])
    response = uds.send(request, timeout=1.0)
    
    assert response is not None, "No response received"
    assert response[0] == 0x6e, "Expected positive response"
    # TODO: Add specific assertions for response data


def test_write_data_by_id_negative_incorrect_length(uds):
    """Test Write Data By Identifier - Negative Response (Incorrect Length)"""
    request = bytes([0x2e])  # Too short
    response = uds.send(request, timeout=1.0)
    
    assert response is not None
    assert response[0] == 0x7F, "Expected negative response"
    assert response[1] == 0x2e, "NRC should reference original SID"
    assert response[2] == 0x13, "Expected NRC 0x13 (Incorrect Message Length)"


def test_write_data_by_id_negative_service_not_supported_in_session(uds):
    """Test Write Data By Identifier - Wrong Session"""
    # TODO: Implement session-specific testing
    pass
