#!/usr/bin/env python3
"""
Auto-generated integration test for UDS Service 0x3e
Tester Present

Generated by generate_tests.py
DO NOT EDIT MANUALLY - Regenerate from spec
"""

import pytest
from uds_test_client import UDSClient

@pytest.fixture
def uds():
    """Create UDS client connection"""
    client = UDSClient(interface='socketcan', channel='vcan0', address=0x7DF)
    yield client
    client.close()


def test_tester_present_positive(uds):
    """Test Tester Present - Positive Response"""
    request = bytes([0x3e, 0x00])
    response = uds.send(request, timeout=1.0)
    
    assert response is not None, "No response received"
    assert response[0] == 0x7e, "Expected positive response"
    # TODO: Add specific assertions for response data


def test_tester_present_negative_incorrect_length(uds):
    """Test Tester Present - Negative Response (Incorrect Length)"""
    request = bytes([0x3e])  # Too short
    response = uds.send(request, timeout=1.0)
    
    assert response is not None
    assert response[0] == 0x7F, "Expected negative response"
    assert response[1] == 0x3e, "NRC should reference original SID"
    assert response[2] == 0x13, "Expected NRC 0x13 (Incorrect Message Length)"


def test_tester_present_negative_service_not_supported_in_session(uds):
    """Test Tester Present - Wrong Session"""
    # TODO: Implement session-specific testing
    pass
